### ISSUE TITLE
Create Relay Resource

### ISSUE THREAD

**Issue by fulviodenza** [fulviodenza/torproxy#2]
Relays are the foundamental component of Tor network.
They exist more kind of relays:

- Guard relays: the first relay (hop) in a Tor circuit;
- Middle relays: that acts as the second hop in the Tor circuit;
- Exit relays: Final relay in a Tor circuit, this is the one that sends traffic out to its destination.

The resource should have a `relayType` field to select which kind of relay you want to run into your cluster.
```
apiVersion: v1beta1
kind: Relay
metadata:
  name: relay
  namespace: default
  labels: 
    tor: hide-me
spec:
  relayType: guard | middle | exit
  nickname: aRelay
  contactInfo: your@e-mail
  orPort: 443
  exitRelay: 0                                              # 1 if the relay is an exit relay
  dirPort: 80                                               # Configuration for exit node relay
  dirPortFrontPage: /path/to/html/file # Configuration for exit node relay
```
